⚡𝐧𝐳𝐱 𝐨𝐧⚡
⚡𝐧𝐳𝐱 𝐨𝐧⚡

diff --git a/modulos/badvpn b/modulos/badvpn
--- a/modulos/badvpn
+++ b/modulos/badvpn
@@ -1,24 +1,31 @@
 #!/bin/bash
+clear
+[[ $(awk -F" " '{print $2}' /usr/lib/nzx) != "@Niltonjuniornzx" ]] && exit 0
 fun_badvpn() {
-    clear
+echo -e "\033[1;37m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     echo -e "\E[44;1;37m            GERENCIAR BADVPN             \E[0m"
+echo -e "\033[1;37m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
+    echo ""
     if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
         echo -e "\033[1;37mPORTAS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'badvpn-ud' | awk {'print $4'} | cut -d: -f2 | xargs)"
     else
         sleep 0.1
     fi
-    var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
+    var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m☑ " || echo -e "\033[1;31m☒ ")
     echo ""
-    echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;37mAtivar badvpn(padrão 7300) $var_sks1 \033[0m"
-    echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;37mAbrir porta\033[0m"
-    echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;37mMenu\033[0m"
+    echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;37mATIVAR BADVPN(PADRÃO 7300) $var_sks1 \033[0m"
+    echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;37mABRIR PORTA\033[0m"
+    echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;37mVOLTAR\033[0m"
     echo ""
-    echo -ne "\033[1;32mO que deseja fazer \033[1;37m?\033[1;37m "
+    echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;37m?\033[1;37m "
     read resposta
     if [[ "$resposta" = '1' ]]; then
         if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
             clear
+echo -e "\033[1;37m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     echo -e "\E[44;1;37m            GERENCIAR BADVPN             \E[0m"
+echo -e "\033[1;37m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
+            echo ""
             fun_stopbad () {
                 sleep 1
                 for pidudpvpn in $(screen -ls | grep ".udpvpn" | awk {'print $1'}); do
@@ -30,16 +37,16 @@ fun_badvpn() {
                 sleep 1
                 screen -wipe >/dev/null
             }
-            echo -e "\033[1;32mDesativando o badvpn\033[1;37m"
+            echo -e "\033[1;32mDESATIVANDO O BADVPN\033[1;37m"
             echo ""
             fun_stopbad
             echo ""
-            echo -e "\033[1;32mBadvpn desativado com sucesso!\033[1;37m"
-            sleep 1
+            echo -e "\033[1;32mBADVPN DESATIVADO COM SUCESSO!\033[1;37m"
+            sleep 3
             fun_badvpn
         else
             clear
-            echo -e "\033[1;32mIniciando o badvpn... \033[0m\n"
+            echo -e "\033[1;32mINICIANDO O BADVPN... \033[0m\n"
             fun_udpon () {
                 screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 5
                 [[ $(grep -wc "udpvpn" /etc/autostart) = '0' ]] && {
@@ -64,26 +71,26 @@ fun_badvpn() {
             inst_udp
             fun_udpon
             echo ""
-            echo -e "\033[1;32mBadvpn ativado com sucesso\033[1;37m"
-            sleep 1
+            echo -e "\033[1;32mBADVPN ATIVADO COM SUCESSO\033[1;37m"
+            sleep 3
             fun_badvpn
         fi
     elif [[ "$resposta" = '2' ]]; then
         if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
             clear
-            echo -e "\E[44;1;37m            badvpn             \E[0m"
+            echo -e "\E[44;1;37m            BADVPN             \E[0m"
             echo ""
-            echo -ne "\033[1;32mQual porta deseja ultilizar \033[1;37m?\033[1;37m: "
+            echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;37m?\033[1;37m: "
             read porta
             [[ -z "$porta" ]] && {
                 echo ""
-                echo -e "\033[1;31mporta invalida!"
-                sleep 1
+                echo -e "\033[1;31mPorta invalida!"
+                sleep 2
                 clear
-				menu
+                menu
             }
             echo ""
-            echo -e "\033[1;32mIniciando o Badvpn na porta \033[1;31m$porta\033[1;37m"
+            echo -e "\033[1;32mINICIANDO O BADVPN NA PORTA \033[1;31m$porta\033[1;37m"
             echo ""
             fun_abrirptbad() {
                 sleep 1
@@ -92,46 +99,13 @@ fun_badvpn() {
             }
             fun_abrirptbad
             echo ""
-            echo -e "\033[1;32mBadvpn ativado com sucesso\033[1;37m"
-            sleep 1
-            fun_badvpn
-        else
-            clear
-            echo -e "\033[1;31mFuncao indisponivel\n\n\033[1;37mative o badvpn primeiro !\033[1;37m"
+            echo -e "\033[1;32mBADVPN ATIVADO COM SUCESSO\033[1;37m"
             sleep 2
             fun_badvpn
-        fi
-    elif [[ "$resposta" = '0 | 00' ]]; then
-        echo ""
-        echo -e "\033[1;31mRetornando...\033[0m"
-        menu
-    else
-        echo ""
-        echo -e "\033[1;31mOpcao invalida !\033[0m"
-        sleep 1
-        fun_badvpn
-    fi
-}
-fun_badvpn
-
-            }
-            echo ""
-            echo -e "\033[1;32mIniciando o badvpn na porta \033[1;31m$porta\033[1;37m"
-            echo ""
-            fun_abrirptbad() {
-                sleep 1
-                screen -dms udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:$porta --max-clients 1000 --max-connections-for-client 5
-                sleep 1
-            }
-            fun_abrirptbad
-            echo ""
-            echo -e "\033[1;32mBadvpn ativado com sucesso\033[1;37m"
-            sleep 1
-            fun_badvpn
         else
             clear
-            echo -e "\033[1;31mFuncao indisponivel\n\n\033[1;37mAtive o badvpn primeiro !\033[1;37m"
-            sleep 1
+            echo -e "\033[1;31mFUNCAO INDISPONIVEL\n\n\033[1;37mATIVE O BADVPN PRIMEIRO !\033[1;37m"
+            sleep 2
             fun_badvpn
         fi
     elif [[ "$resposta" = '0' ]]; then
